### PR TITLE
Fix calendar stuff

### LINKED ISSUE #15: Missing August 31st in calendar?
The date 8/31 is missing from the calendar in the month-view.

### LINKED ISSUE #16: Default view for calendar — change from week to month
Can we make the month-view the default?

### PR DESCRIPTION
**Pull request by mitchellhenke**
Closes #15, #14 

For #14, if an event start or end time is 00:00, it will show TBD.

I did not do #16, as I wasn't sure how defaulting to month would affect mobile (cc @nickgartmann)

As mentioned in Slack, the dates for events can't use curly quotes, long dashes, and has to be in `09:00` format.

### CODE REVIEW

File: assets/js/calendar.js [hunk 1]
```diff
@@ -37,7 +41,7 @@ new Vue({
     currentMonth: new Date().getMonth(),
     currentYear: new Date().getFullYear(),
     display: "week",
-    currentWeek: parseInt((new Date().getDate() + (new Date(new Date().getFullYear(), new Date().getMonth(), 1).getDay())) / 7) + 1
+    currentWeek: Math.ceil(new Date().getDate() / 7)
```
Comment (nickgartmann) [inline assets/js/calendar.js:44]: Niiiiice!

**Review by nickgartmann — APPROVED** [review]
🙌 @mitchellhenke 🙌

**Comment by mitchellhenke** [comment]
https://github.com/MarchonMilwaukee/MarchonMilwaukee.github.io/pull/17/commits/2938ea65e5cca8906a95095f2573af2105f47e91 seems to fix the missing last day of month phenomenon
